- id: '1768744899946'
  alias: Control boiler
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.trvs_heating
    to:
  conditions: []
  actions:
  - action: switch.turn_{{ trigger.to_state.state }}
    metadata: {}
    data: {}
    target:
      entity_id: switch.sonoff_zbm5_1c_80_86
  mode: single
- id: '1769027088861'
  alias: Lounge TRV sync
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - climate.lounge_trv_master_thermostat
    attribute: temperature
  actions:
  - action: climate.set_temperature
    metadata: {}
    target:
      entity_id: climate.lounge_trv_thermostat
    data:
      temperature: '{{ state_attr(''climate.lounge_trv_master_thermostat'', ''temperature'')
        }}'
      hvac_mode: heat
  mode: single
- id: '1771274759486'
  alias: Auto turn off heating
  description: Turns off the heating at a certain time
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: script.set_rooms_temp
    metadata: {}
    data:
      base_target_temp: input_number.off_temp
  mode: single
